---
- name: Initialize Nodes
  hosts: k8s
  become: true
  tasks:
    - name: Install Base Packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg
    - name: Set firewall rules UFW
      shell:  |
          sudo ufw allow 6443/tcp
          sudo ufw allow 2379/tcp
          sudo ufw allow 2380/tcp
          sudo ufw allow 10250/tcp
          sudo ufw allow 10251/tcp
          sudo ufw allow 10252/tcp
          sudo ufw allow 10255/tcp
          sudo ufw reload
    - name: Disable SWAP
      shell: |
          swapoff -a
    - name: Disable SWAP fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        line: '#\0'
        backrefs: yes
    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Add Docker GPGP
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: Get system architecture
      command: dpkg --print-architecture
      register: system_arch
      changed_when: false
    - name: Get OS codename
      shell: . /etc/os-release && echo "$VERSION_CODENAME"
      register: os_codename
      changed_when: false
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ os_codename.stdout }} stable"
        filename: docker
        state: present
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose
    - name: Set SystemdCgroup
      shell: |
        containerd config default | sudo tee /etc/containerd/config.toml | grep SystemdCgroup
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Download Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        dest: /tmp/k8s.key
        mode: '0644'

    - name: Import Kubernetes GPG key
      shell: |
        gpg --dearmor < /tmp/k8s.key > /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        rm /tmp/k8s.key
    - name: Add Kubernetes 1.32 repository
      copy:
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /\n"
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: '0644'
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Kube Utils
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubelet
    - name: Start Kubelet
      service:
        name: kubelet
        state: started
        enabled: yes
