---
- name: Setup Kubernetes Worker Nodes
  hosts: k8s_worker_nodes
  become: true
  tasks:
    - name: Reset existing Kubernetes configuration
      command: kubeadm reset -f

    - name: Remove existing Kubernetes files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes/kubelet.conf
        - /etc/kubernetes/pki
        - /etc/kubernetes/bootstrap-kubelet.conf

    - name: Read join command
      local_action:
        module: slurp
        src: join-command.txt
      register: join_command_file
      become: false

    - name: Join the cluster
      command: "{{ join_command_file['content'] | b64decode }} --ignore-preflight-errors=all --v=5"

